export const ActionTypes = {
    SET_MONTHLY_REPORT: "SET_MONTHLY_REPORT",
    SET_INVOICE_REPORT: "SET_INVOICE_REPORT",
    SET_TOTALCASH_REPORT :"SET_TOTALCASH_REPORT",
    SET_ACCOUNT_REPORT: "SET_ACCOUNT_REPORT"
}